### ISSUE TITLE
Program Dies on launch, "Restart Warframe not in admin mode" neither Warframe or Steam are in admin mode

### ISSUE THREAD

**Issue by Driller3900** [WFCD/WFinfo#194]
[8/18/2021 4:08:30 AM 9.4.2]   Checking for Updates to Databases
[8/18/2021 4:08:31 AM 9.4.2]   Market Databases are up to date
[8/18/2021 4:08:31 AM 9.4.2]   Prime Database is up to date
[8/18/2021 4:08:32 AM 9.4.2]   Starting LogCapture
[8/18/2021 4:08:32 AM 9.4.2]   WFInfo has launched successfully
[8/18/2021 4:08:32 AM 9.4.2]   Found Warframe Process: ID - 17768, MainTitle - Warframe, Process Name - Warframe.x64
[8/18/2021 4:08:32 AM 9.4.2]   Failed to get Warframe process due to: Access is denied
[8/18/2021 4:08:34 AM - Still in custom entrypoint]   MyHandler caught: Access is denied
[8/18/2021 4:08:34 AM - Still in custom entrypoint]   Runtime terminating: True
[8/18/2021 4:08:34 AM - Still in custom entrypoint]      at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at WFInfo.Main.OnMouseAction(MouseButton key)
   at WFInfo.LowLevelListener.HookCallbackM(Int32 nCode, IntPtr wParam, IntPtr lParam)

**Comment by dapal-003** [comment]
That error is only throw when Warframe is running at a higher elevation
than wfinfo. You can try launching wfinfo as admin and see if that changes
anything. Although i won't recommend you using it like that daily

**Comment by Driller3900** [comment]
Okay, i'll try that tomorrow, thanks!
